Repository NastMz/UniRutas, pull requests merged in 2023-10, with the labels that each got.

#2 Feature/add repository pattern
  src/main/java/com/unirutas/Main.java
  src/main/java/com/unirutas/annotations/Column.java
  src/main/java/com/unirutas/annotations/PrimaryKey.java
  src/main/java/com/unirutas/annotations/Table.java
  src/main/java/com/unirutas/controllers/UserController.java
  src/main/java/com/unirutas/core/ConnectionPool.java
  src/main/java/com/unirutas/models/Administrative.java
  src/main/java/com/unirutas/models/Driver.java
  src/main/java/com/unirutas/models/Person.java
  src/main/java/com/unirutas/models/Student.java
  src/main/java/com/unirutas/models/User.java
  src/main/java/com/unirutas/repository/GenericDTO.java
  src/main/java/com/unirutas/repository/implementation/AdministrativeRepository.java
  src/main/java/com/unirutas/repository/implementation/DatabaseManager.java
  src/main/java/com/unirutas/repository/implementation/GenericRepository.java
  src/main/java/com/unirutas/repository/implementation/StudentRepository.java
  src/main/java/com/unirutas/repository/interfaces/IDatabaseManager.java
  src/main/java/com/unirutas/repository/interfaces/IRepository.java
  src/main/java/com/unirutas/services/implementation/AdministrativeServices.java
  src/main/java/com/unirutas/services/implementation/StudentServices.java
  src/main/java/com/unirutas/services/interfaces/UserServices.java
Labels: enhancement

#4 Added functions to get Date and Hour from Database engine
  src/main/java/com/unirutas/core/database/manager/implementation/nosql/implementation/MongoDBDatabaseManager.java
  src/main/java/com/unirutas/core/database/manager/implementation/sql/implementation/SQLDatabaseManager.java
  src/main/java/com/unirutas/core/database/manager/interfaces/IDatabaseManager.java
  src/main/java/com/unirutas/core/database/repository/implementation/nosql/MongoDBGenericRepository.java
  src/main/java/com/unirutas/core/database/repository/implementation/sql/SQLGenericRepository.java
  src/main/java/com/unirutas/core/database/repository/interfaces/IRepository.java
  src/main/java/com/unirutas/services/implementation/AdministrativeServices.java
  src/main/java/com/unirutas/services/implementation/StudentServices.java
Labels: enhancement

#5 Refactor/models
  src/main/java/com/unirutas/Main.java
  src/main/java/com/unirutas/controllers/BusController.java
  src/main/java/com/unirutas/controllers/JourneyController.java
  src/main/java/com/unirutas/controllers/ServiceController.java
  src/main/java/com/unirutas/models/AdministrativeAlert.java
  src/main/java/com/unirutas/models/Alert.java
  src/main/java/com/unirutas/models/Bus.java
  src/main/java/com/unirutas/models/Coordinate.java
  src/main/java/com/unirutas/models/Direction.java
  src/main/java/com/unirutas/models/DriverBus.java
  src/main/java/com/unirutas/models/Journey.java
  src/main/java/com/unirutas/models/JourneySection.java
  src/main/java/com/unirutas/models/JourneyStop.java
  src/main/java/com/unirutas/models/Route.java
  src/main/java/com/unirutas/models/Schedule.java
  src/main/java/com/unirutas/models/Section.java
  src/main/java/com/unirutas/models/SectionCoordinate.java
  src/main/java/com/unirutas/models/Service.java
  src/main/java/com/unirutas/models/ServiceAlert.java
  src/main/java/com/unirutas/models/ServiceBus.java
  src/main/java/com/unirutas/models/ServiceSchedule.java
  src/main/java/com/unirutas/models/Stop.java
  src/main/java/com/unirutas/models/Student.java
  src/main/java/com/unirutas/models/StudentAlert.java
  src/main/java/com/unirutas/models/StudentSubscription.java
  src/main/java/com/unirutas/models/UserAlert.java
Labels: refactor

#6 Feature/dependency injection
  src/main/java/com/unirutas/Main.java
  src/main/java/com/unirutas/controllers/UserController.java
  src/main/java/com/unirutas/core/database/repository/CrudRepository.java
  src/main/java/com/unirutas/core/database/repository/implementation/nosql/MongoDBGenericRepository.java
  src/main/java/com/unirutas/core/database/repository/implementation/sql/SQLGenericRepository.java
  src/main/java/com/unirutas/core/dependency/annotations/Factory.java
  src/main/java/com/unirutas/core/dependency/annotations/FactoryMethod.java
  src/main/java/com/unirutas/core/dependency/annotations/Implementation.java
  src/main/java/com/unirutas/core/dependency/annotations/Inject.java
  src/main/java/com/unirutas/core/dependency/annotations/Repository.java
  src/main/java/com/unirutas/core/dependency/annotations/Singleton.java
  src/main/java/com/unirutas/core/dependency/annotations/SingletonMethod.java
  src/main/java/com/unirutas/core/dependency/containers/implementations/DependencyContainer.java
  src/main/java/com/unirutas/core/dependency/containers/interfaces/IDependencyContainer.java
  src/main/java/com/unirutas/core/dependency/injector/implementation/DependencyInjector.java
  src/main/java/com/unirutas/core/dependency/injector/interfaces/IDependencyInjector.java
  src/main/java/com/unirutas/core/dependency/utils/DependencyScanner.java
  src/main/java/com/unirutas/core/dependency/validators/DependencyValidator.java
  src/main/java/com/unirutas/repository/AdministrativeRepository.java
  src/main/java/com/unirutas/repository/StudentRepository.java
  src/main/java/com/unirutas/services/implementation/AdministrativeServices.java
  src/main/java/com/unirutas/services/implementation/StudentServices.java
Labels: enhancement, partial

#8 Feature/Add Template Pattern
  pom.xml
  src/main/java/com/unirutas/Main.java
  src/main/java/com/unirutas/controllers/AlertController.java
  src/main/java/com/unirutas/controllers/StudentSubscriptionController.java
  src/main/java/com/unirutas/core/builder/query/implementation/nosql/MongoDBCustomQueryBuilder.java
  src/main/java/com/unirutas/core/builder/query/implementation/sql/SQLCustomQueryBuilder.java
  src/main/java/com/unirutas/core/builder/query/interfaces/ICustomQueryBuilder.java
  src/main/java/com/unirutas/core/database/repository/utils/RepositoryUtils.java
  src/main/java/com/unirutas/core/factory/builder/implementation/NoSQLCustomQueryBuilderFactory.java
  src/main/java/com/unirutas/core/factory/builder/implementation/SQLCustomQueryBuilderFactory.java
  src/main/java/com/unirutas/core/factory/builder/interfaces/ICustomQueryBuilderFactory.java
  src/main/java/com/unirutas/helpers/notification/implementation/AdministrativeAlertNotification.java
  src/main/java/com/unirutas/helpers/notification/implementation/StudentAlertNotification.java
  src/main/java/com/unirutas/helpers/notification/template/AlertNotification.java
  src/main/java/com/unirutas/repository/StudentSubscriptionRepository.java
  src/main/java/com/unirutas/services/implementation/StudentSubscriptionServices.java
  src/main/resources/logback.xml
Labels: enhancement
