Repository NastMz/UniRutas, pull requests merged in 2023-11, with the labels that each got.

#9 Improve Dependency Inclusion and Classpath Scanning Logic
  dependency-reduced-pom.xml
  pom.xml
  src/main/java/com/unirutas/core/database/config/implementation/sql/implementation/SQLDatabaseConfig.java
  src/main/java/com/unirutas/core/database/connection/implementation/sql/implementation/SQLConnectionPool.java
  src/main/java/com/unirutas/core/dependency/containers/implementations/DependencyContainer.java
  src/main/java/com/unirutas/core/dependency/utils/DependencyScanner.java
  src/main/java/com/unirutas/core/dependency/validators/DependencyValidator.java
  src/main/java/com/unirutas/core/utils/ClasspathScanner.java
  src/main/resources/core-config.xml
Labels: refactor, fix

#10 Feature/Add Chain Of Responsibility Pattern
  .gitignore
  src/main/java/com/unirutas/Main.java
  src/main/java/com/unirutas/auth/handlers/implementation/BasicAuthenticationHandler.java
  src/main/java/com/unirutas/auth/handlers/implementation/DefaultAuthenticationHandler.java
  src/main/java/com/unirutas/auth/handlers/implementation/MultiFactorAuthenticationHandler.java
  src/main/java/com/unirutas/auth/handlers/implementation/PhoneAuthenticationHandler.java
  src/main/java/com/unirutas/auth/handlers/implementation/SecurityPhraseAuthenticationHandler.java
  src/main/java/com/unirutas/auth/handlers/interfaces/IAuthenticationHandler.java
  src/main/java/com/unirutas/auth/validators/BasicValidators.java
  src/main/java/com/unirutas/auth/validators/MultiFactorValidators.java
  src/main/java/com/unirutas/auth/validators/PhoneValidators.java
  src/main/java/com/unirutas/auth/validators/SecurityPhraseValidators.java
  src/main/java/com/unirutas/controllers/AuthenticationController.java
  src/main/java/com/unirutas/controllers/UserController.java
  src/main/java/com/unirutas/models/Administrative.java
  src/main/java/com/unirutas/models/Student.java
  src/main/java/com/unirutas/models/User.java
  src/main/java/com/unirutas/repository/AdministrativeRepository.java
  src/main/java/com/unirutas/repository/StudentRepository.java
  src/main/java/com/unirutas/services/implementation/AdministrativeServices.java
  src/main/java/com/unirutas/services/implementation/StudentServices.java
  src/main/java/com/unirutas/services/interfaces/UserServices.java
Labels: enhancement

#11 Added create and drop sql for database
  docs/CREATE.sql
  docs/DROP.sql
Labels: documentation

#12 The Command pattern has been implemented
  src/main/java/com/unirutas/Main.java
  src/main/java/com/unirutas/auth/services/AuthenticationService.java
  src/main/java/com/unirutas/commands/implementations/ChangePasswordCommand.java
  src/main/java/com/unirutas/commands/interfaces/ICommand.java
  src/main/java/com/unirutas/controllers/UserController.java
  src/main/java/com/unirutas/services/implementation/UserServices.java
  src/main/resources/database.properties
Labels: enhancement, help wanted, partial
